language: go
sudo: false

env:
  global:
    - PROTOC_RELEASE="https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip"
    - PROTOC_TARGET="${HOME}/protoc"
    - PATH="${PROTOC_TARGET}/bin:${PATH}"

cache:
  - "${HOME}/protoc"
  - "${HOME}/gopath/src/github.com/arc82/protoc-gen-doc/vendor"

go:
  - 1.8.x
  - master

install:
  - if [ ! -d "${PROTOC_TARGET}" ]; then curl -fsSL "$PROTOC_RELEASE" > "${PROTOC_TARGET}.zip"; fi
  - if [ -f "${PROTOC_TARGET}.zip" ]; then unzip "${PROTOC_TARGET}.zip" -d "${PROTOC_TARGET}"; fi
  - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
  - go get -u github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout tags/v0.12.3 && go install && cd -
  - glide install

script:
  - make test
  - make bench

notifications:
  email: false
